filebeat.inputs:
  - type: log
    paths:
      - /var/log/*access.log
    encoding: utf-8
    fields:
      topic: nginx-log
    scan_frequency: 1s
    harvester_buffer_size: 16384
    tail_files: false
    close_eof: true
    clean_removed: true
#  - type: log
#    paths:
#      - /var/lib/mysql/*mysql.slow.log
#    encoding: utf-8
#    fields:
#      topic: mysql-log
#    scan_frequency: 1s
#    harvester_buffer_size: 16384
#    tail_files: false
#    close_eof: true
#    clean_removed: true
  - type: log
    enabled: true
    close_rename: true
    close_remove: true
    close_inactive: 10m
    paths:
      - /var/lib/mysql/mysql.slow.log
    scan_frequency: 1m
    backoff: 1s
    max_backoff: 10s
    backoff_factor: 2
    harvester_limit: 10
    multiline.pattern: '^(# Time)'
    multiline.negate: true
    multiline.match: after
    multiline.timeout: 5s
    fields:
      topic: mysql-log




processors:
  - drop_fields:
      fields: ["ecs", "input", "host", "agent", "log.offset"]
      ignore_missing: true

#------------------------------- Kafka output ---------------------------------
output.kafka:
  enabled: true
  hosts: ["kafka:9092"]
  topic: elk-%{[fields.topic]}
  worker: 2
  keep_alive: 60
  required_acks: 1
